import { Arrow } from "./Arrow";

export function Reviews({ testimonials, testimonial, expanded, dragging, dragOffset, onSelect, onToggleExpanded, onTouchStart, onTouchMove, onTouchEnd, onTouchCancel, justdialReviewsUrl }) {
  const previous = () => onSelect(testimonial - 1);
  const next = () => onSelect(testimonial + 1);
  return <section className="reviews" id="reviews" data-reveal>
    <div className="reviews-heading"><p className="eyebrow">Words from our community</p><h2>Practice,<br /><em>in their words.</em></h2><p>Reflections from students who have made Yogalaya part of their everyday lives.</p></div>
    <div className="review-stage">{testimonials[testimonial].featured && <span className="featured-review-label">Featured review</span>}<span className="review-mark" aria-hidden="true">“</span><blockquote className={expanded ? "is-expanded" : "is-clamped"} key={testimonial}>{testimonials[testimonial].quote}</blockquote><button className="review-read-more" type="button" onClick={onToggleExpanded} aria-expanded={expanded}>{expanded ? "Show less" : "Read full review"}</button><div className="review-person" key={`person-${testimonial}`}><strong>{testimonials[testimonial].name}</strong><span>{testimonials[testimonial].detail}</span></div><div className="review-progress" aria-hidden="true"><span style={{ width: `${((testimonial + 1) / testimonials.length) * 100}%` }} /></div><div className="testimonial-controls"><button onClick={() => onSelect((testimonial - 1 + testimonials.length) % testimonials.length)} aria-label="Previous review">←</button><span>{String(testimonial + 1).padStart(2, "0")} / {String(testimonials.length).padStart(2, "0")}</span><button onClick={() => onSelect((testimonial + 1) % testimonials.length)} aria-label="Next review">→</button></div><a className="all-reviews-link" href={justdialReviewsUrl} target="_blank" rel="noreferrer">See all reviews <Arrow /></a></div>
    <div className="review-directory" aria-label="Choose a review">{testimonials.map((review, index) => <button className={testimonial === index ? "is-active" : ""} onClick={() => onSelect(index)} key={review.name} aria-pressed={testimonial === index}><span>{String(index + 1).padStart(2, "0")}</span><strong>{review.name}</strong><small>{review.detail}</small></button>)}</div>
    <div className="mobile-reviews" aria-label="Student reviews carousel"><div className="mobile-review-viewport" onTouchStart={onTouchStart} onTouchMove={onTouchMove} onTouchEnd={onTouchEnd} onTouchCancel={onTouchCancel}><div className={`mobile-review-track ${dragging ? "is-dragging" : ""}`} style={{ "--mobile-review-index": testimonial, "--mobile-review-drag": dragOffset }}>{testimonials.map((review, index) => { const active = testimonial === index; return <article className={`mobile-review-card ${active ? "is-active" : ""}`} style={{ "--review-distance": index - testimonial }} key={`mobile-${review.name}`} aria-hidden={!active}><div className="mobile-review-card-top"><span>{String(index + 1).padStart(2, "0")}</span>{review.featured && <small>Featured review</small>}</div><span className="mobile-review-mark" aria-hidden="true">“</span><blockquote className={active && expanded ? "is-expanded" : "is-clamped"}>{review.quote}</blockquote>{active && <button className="mobile-review-more" type="button" onClick={onToggleExpanded} aria-expanded={expanded}>{expanded ? "Show less" : "Read full review"}</button>}<footer className="mobile-review-author"><strong>{review.name}</strong><span>{review.detail}</span></footer></article>; })}</div></div><div className="mobile-review-controls"><button type="button" onClick={previous} disabled={testimonial === 0} aria-label="Previous review">←</button><div className="mobile-review-count"><strong>{String(testimonial + 1).padStart(2, "0")}</strong><span>/ {String(testimonials.length).padStart(2, "0")}</span></div><button type="button" onClick={next} disabled={testimonial === testimonials.length - 1} aria-label="Next review">→</button></div><div className="mobile-review-progress" aria-hidden="true"><span style={{ width: `${((testimonial + 1) / testimonials.length) * 100}%` }} /></div><a className="mobile-all-reviews-link" href={justdialReviewsUrl} target="_blank" rel="noreferrer">See all reviews on Google <Arrow /></a></div>
  </section>;
}
